Fix FakeRedisMixin.from_url for unix sockets
fakeredis.FakeRedisMixin.from_url is broken for unix sockets.
fakeredis.FakeRedis.from_url("unix://a/b/c") results in
TypeError: __init__() got an unexpected keyword argument 'path'
This was caused by PR #304.